name: Continuous Integration

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  LATEST_NODE_VERSION: 16

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run unit tests
        run: yarn test:ci

      - name: Publish code coverage
        if: matrix.node == env.LATEST_NODE_VERSION
        run: echo Not Implemented Yet

      - name: Run integration tests
        run: |
          docker-compose up -d
          yarn --cwd ./integration/app
          yarn test:ci:integration
        env:
          NODE_ENV: ci
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
